env:
    MANIFEST: https://github.com/Spark-Rom/manifest -b pyro
    DEVICE: fleur
    OEM: xiaomi
    DT_LINK: https://github.com/RT1648/device_xiaomi_fleur.git
    DT_PATH: device/xiaomi/fleur
    VT_LINK: https://github.com/RT1648/proprietary_vendor_xiaomi_ims-fleur.git
    VT_PATH: vendor/xiaomi/fleur
    EXTRA_CMD: export WITH_GAPPS=true
    LUNCH_COMBO: spark_${DEVICE}-userdebug
    OUTPUT: Spark*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[3169edd4c01ba48f5acdf3e095711295a4cd13bb5e1d4cb3b0b608286ee6339285fe0d611b7bd906d6b9e8d5f5e8541f]
    URI: https://fleur.shazuxd7.workers.dev/0:/Rt/ccache.tar.gz
    ROM_U: 1
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Storage-Checker_script:
      - ./d0wnl0ad
 
  Sync_script:
      - ./syn0

  Build_script:
      - ./bu1ld

  upload_script:
      - sh upl0ad
