env:
    MANIFEST: https://github.com/SuperiorOS/manifest.git -b thirteen
    DEVICE: X01BD
    OEM: asus
    DT_LINK: https://github.com/RT1648/android_device_asus_X01BD.git
    DT_PATH: device/asus/X01BD
    VT_LINK: https://github.com/RT1648/proprietary_vendor_asus.git
    KT_LINK: https://github.com/RT1648/android_kernel_asus_sdm660.git
    CT_LINK: https://github.com/RT1648/android_device_asus_sdm660-common.git
    VT_PATH: vendor/asus
    KT_PATH: kernel/asus/sdm660
    CT_PATH: device/asus/sdm660-common
    EXTRA_CMD: export WITH_GAPPS=true
    LUNCH_COMBO: superior_${DEVICE}-userdebug
    OUTPUT: Superior*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[3169edd4c01ba48f5acdf3e095711295a4cd13bb5e1d4cb3b0b608286ee6339285fe0d611b7bd906d6b9e8d5f5e8541f]
    URI: 
    ROM_U: 0
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G



  Storage-Checker_script:
      - ./d0wnl0ad
  
  Sync_script:
      - ./syn0

  Build_script:
      - ./bu1ld

  upload_script:
      - sh upl0ad
