env:
    MANIFEST: https://github.com/SkylineUI/manifest -b aosp-13
    DEVICE: RMX1901
    OEM: realme
    DT_LINK: https://github.com/Shravan55555/device_realme_RMX1901.git -b 13
    DT_PATH: device/realme/RMX1901
    VT_LINK: https://github.com/SlicKker-001/vendor_realme_RMX1901.git  -b 13
    KT_LINK: https://github.com/ashim-anwar/kernel_realme_RMX1901.git -b x.337-KSU
    VT_PATH: vendor/realme/RMX1901
    KT_PATH: kernel/realme/RMX1901
    LUNCH_COMBO: aosp_${DEVICE}-userdebug
    OUTPUT: S*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[!f1d6be2955abc0e707d19e911e742d164c53d4abd3136d5cda5bc0c25a09e9a7f8668ea263e382612f3f8de8f51a6413!]
    URI: https://github.com/exampleurl
    ROM_U: 1
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m
  container:
      image: ghcr.io/satorugojo2k23/ubuntu:latest
      cpu: 8
      memory: 32G

  Storage-Checker_script:
      - ./d0wnl0ad

  Sync_script:
      - ./syn0

  Build_script:
      - ./bu1ld

  upload_script:
      - sh upl0ad
