#!/bin/bash
cd ~/work/device/realme/RMX1901/prebuilts

cd ~/work
bash ~/work/device/realme/RMX1901/pat*/pat*.sh
. build/envsetup.sh
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 60G
ccache -o compression=true
ccache -z
lunch "$LUNCH_COMBO"
make bacon -j8 & sleep 90m
